package it.qsbl.com.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class OrderCart {

    private  String image;

    private String name;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.cart_id
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Integer cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.customer_id
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.product_id
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.product_amount
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Integer productAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.price
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.add_time
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.modified_time
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_cart.string_to_html
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    private String stringToHtml;


}