package it.qsbl.com.domain;

import java.math.BigDecimal;
import java.util.Date;

public class OrderMaster {
    private Integer orderId;

    private Long orderSn;

    private Integer customerId;

    private String shippingUser;

    private Short province;

    private Short city;

    private Short district;

    private String address;

    private Byte paymentMethod;

    private BigDecimal orderMoney;

    private BigDecimal districtMoney;

    private BigDecimal shippingMoney;

    private BigDecimal paymentMoney;

    private String shippingCompName;

    private String shippingSn;

    private Date createTime;

    private Date shippingTime;

    private Date payTime;

    private Date receiveTime;

    private Byte orderStatus;

    private Integer orderPoint;

    private String invoiceTime;

    private Date modifiedTime;

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Long getOrderSn() {
        return orderSn;
    }

    public void setOrderSn(Long orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.customer_id
     *
     * @return the value of order_master.customer_id
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.customer_id
     *
     * @param customerId the value for order_master.customer_id
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_user
     *
     * @return the value of order_master.shipping_user
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public String getShippingUser() {
        return shippingUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_user
     *
     * @param shippingUser the value for order_master.shipping_user
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setShippingUser(String shippingUser) {
        this.shippingUser = shippingUser == null ? null : shippingUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.province
     *
     * @return the value of order_master.province
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Short getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.province
     *
     * @param province the value for order_master.province
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setProvince(Short province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.city
     *
     * @return the value of order_master.city
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Short getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.city
     *
     * @param city the value for order_master.city
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setCity(Short city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.district
     *
     * @return the value of order_master.district
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Short getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.district
     *
     * @param district the value for order_master.district
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setDistrict(Short district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.address
     *
     * @return the value of order_master.address
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.address
     *
     * @param address the value for order_master.address
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.payment_method
     *
     * @return the value of order_master.payment_method
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.payment_method
     *
     * @param paymentMethod the value for order_master.payment_method
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_money
     *
     * @return the value of order_master.order_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public BigDecimal getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_money
     *
     * @param orderMoney the value for order_master.order_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setOrderMoney(BigDecimal orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.district_money
     *
     * @return the value of order_master.district_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public BigDecimal getDistrictMoney() {
        return districtMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.district_money
     *
     * @param districtMoney the value for order_master.district_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setDistrictMoney(BigDecimal districtMoney) {
        this.districtMoney = districtMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_money
     *
     * @return the value of order_master.shipping_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public BigDecimal getShippingMoney() {
        return shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_money
     *
     * @param shippingMoney the value for order_master.shipping_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setShippingMoney(BigDecimal shippingMoney) {
        this.shippingMoney = shippingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.payment_money
     *
     * @return the value of order_master.payment_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public BigDecimal getPaymentMoney() {
        return paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.payment_money
     *
     * @param paymentMoney the value for order_master.payment_money
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setPaymentMoney(BigDecimal paymentMoney) {
        this.paymentMoney = paymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_comp_name
     *
     * @return the value of order_master.shipping_comp_name
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public String getShippingCompName() {
        return shippingCompName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_comp_name
     *
     * @param shippingCompName the value for order_master.shipping_comp_name
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setShippingCompName(String shippingCompName) {
        this.shippingCompName = shippingCompName == null ? null : shippingCompName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_sn
     *
     * @return the value of order_master.shipping_sn
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public String getShippingSn() {
        return shippingSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_sn
     *
     * @param shippingSn the value for order_master.shipping_sn
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setShippingSn(String shippingSn) {
        this.shippingSn = shippingSn == null ? null : shippingSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.create_time
     *
     * @return the value of order_master.create_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.create_time
     *
     * @param createTime the value for order_master.create_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.shipping_time
     *
     * @return the value of order_master.shipping_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Date getShippingTime() {
        return shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.shipping_time
     *
     * @param shippingTime the value for order_master.shipping_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setShippingTime(Date shippingTime) {
        this.shippingTime = shippingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.pay_time
     *
     * @return the value of order_master.pay_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.pay_time
     *
     * @param payTime the value for order_master.pay_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.receive_time
     *
     * @return the value of order_master.receive_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Date getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.receive_time
     *
     * @param receiveTime the value for order_master.receive_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setReceiveTime(Date receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_status
     *
     * @return the value of order_master.order_status
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Byte getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_status
     *
     * @param orderStatus the value for order_master.order_status
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setOrderStatus(Byte orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.order_point
     *
     * @return the value of order_master.order_point
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Integer getOrderPoint() {
        return orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.order_point
     *
     * @param orderPoint the value for order_master.order_point
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setOrderPoint(Integer orderPoint) {
        this.orderPoint = orderPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.invoice_time
     *
     * @return the value of order_master.invoice_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public String getInvoiceTime() {
        return invoiceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.invoice_time
     *
     * @param invoiceTime the value for order_master.invoice_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setInvoiceTime(String invoiceTime) {
        this.invoiceTime = invoiceTime == null ? null : invoiceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_master.modified_time
     *
     * @return the value of order_master.modified_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_master.modified_time
     *
     * @param modifiedTime the value for order_master.modified_time
     *
     * @mbg.generated Mon Apr 22 09:09:04 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}