package it.qsbl.com.domain;

import java.util.Date;

public class ProductComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.comment_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.order_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.customer_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.title
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.content
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.audit_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Byte auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.audit_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comment.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.comment_id
     *
     * @return the value of product_comment.comment_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.comment_id
     *
     * @param commentId the value for product_comment.comment_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.product_id
     *
     * @return the value of product_comment.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.product_id
     *
     * @param productId the value for product_comment.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.order_id
     *
     * @return the value of product_comment.order_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.order_id
     *
     * @param orderId the value for product_comment.order_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.customer_id
     *
     * @return the value of product_comment.customer_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.customer_id
     *
     * @param customerId the value for product_comment.customer_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.title
     *
     * @return the value of product_comment.title
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.title
     *
     * @param title the value for product_comment.title
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.content
     *
     * @return the value of product_comment.content
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.content
     *
     * @param content the value for product_comment.content
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.audit_status
     *
     * @return the value of product_comment.audit_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.audit_status
     *
     * @param auditStatus the value for product_comment.audit_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.audit_time
     *
     * @return the value of product_comment.audit_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.audit_time
     *
     * @param auditTime the value for product_comment.audit_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comment.modified_time
     *
     * @return the value of product_comment.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comment.modified_time
     *
     * @param modifiedTime the value for product_comment.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}