package it.qsbl.com.domain;

import java.util.Date;

public class ProductRicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.product_pic_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productPicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.pic_desc
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String picDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.pic_url
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.master
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Byte master;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.pic_order
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Byte picOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.pic_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Byte picStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pic_info.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.product_pic_id
     *
     * @return the value of product_pic_info.product_pic_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public String getProductPicId() {
        return productPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.product_pic_id
     *
     * @param productPicId the value for product_pic_info.product_pic_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setProductPicId(String productPicId) {
        this.productPicId = productPicId == null ? null : productPicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.product_id
     *
     * @return the value of product_pic_info.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.product_id
     *
     * @param productId the value for product_pic_info.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.pic_desc
     *
     * @return the value of product_pic_info.pic_desc
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public String getPicDesc() {
        return picDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.pic_desc
     *
     * @param picDesc the value for product_pic_info.pic_desc
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setPicDesc(String picDesc) {
        this.picDesc = picDesc == null ? null : picDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.pic_url
     *
     * @return the value of product_pic_info.pic_url
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.pic_url
     *
     * @param picUrl the value for product_pic_info.pic_url
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.master
     *
     * @return the value of product_pic_info.master
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Byte getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.master
     *
     * @param master the value for product_pic_info.master
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setMaster(Byte master) {
        this.master = master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.pic_order
     *
     * @return the value of product_pic_info.pic_order
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Byte getPicOrder() {
        return picOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.pic_order
     *
     * @param picOrder the value for product_pic_info.pic_order
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setPicOrder(Byte picOrder) {
        this.picOrder = picOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.pic_status
     *
     * @return the value of product_pic_info.pic_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Byte getPicStatus() {
        return picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.pic_status
     *
     * @param picStatus the value for product_pic_info.pic_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setPicStatus(Byte picStatus) {
        this.picStatus = picStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pic_info.modified_time
     *
     * @return the value of product_pic_info.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pic_info.modified_time
     *
     * @param modifiedTime the value for product_pic_info.modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}