package it.qsbl.com.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class ProductInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_type_id
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_weight
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private BigDecimal productWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_price
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_image
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_stock
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer productStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_status
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer productStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_user
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.production_date
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date productionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_shelf_life
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Integer productShelfLife;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_insert_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date productInsertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_modified_time
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private Date productModifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_desc
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_text
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    private String productText;
}