package it.qsbl.com.dao;


import it.qsbl.com.domain.HouseDetail;

public interface HouseDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int insert(HouseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int insertSelective(HouseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    HouseDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int updateByPrimaryKeySelective(HouseDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table house_detail
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int updateByPrimaryKey(HouseDetail record);
}