package it.qsbl.com.dao;

import it.qsbl.com.domain.Menu;
import it.qsbl.com.domain.vo.MenuVO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

@Mapper
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    Menu selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbg.generated Tue Apr 23 22:41:41 CST 2019
     */
    int updateByPrimaryKey(Menu record);

    @Select("select * from menu where rid = #{rid} and pid = -1")
    List<Menu> getALLmenuByRroleIDPrent(@Param("rid") Integer rid);

    @Select("select m.* from (select * from menu_role where rid = #{rid} ) as mr left join menu m on mr.mid = m.mid where m.pid = #{pid}")
    List<Menu> getALLmenuByRroleIDChildren(@Param("rid") Integer rid,
                                        @Param("pid") Integer pid);
/*
    @Select("select * from menu where rid = #{rid} and pid = #{pid}")
    List<Menu> getALLmenuByRroleIDChildren(@Param("rid") Integer rid,
                                        @Param("pid") Integer pid);
*/


    @Select("select * from menu")
    List<Menu> getAllMenus();

    /**
     * 封装方法 主要负责角色分配权限回显封装
     * @return
     */
    @Select("select * from menu")
    List<MenuVO> getAllMenusToMenuVO();

    @Select("select * from menu where pid = #{pid}")
    List<Menu> getAllMenusOfParent(@Param("pid") Integer  pid);

}