package it.qsbl.com.dao;

import it.qsbl.com.domain.OrderCart;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface OrderCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int deleteByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int insert(OrderCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int insertSelective(OrderCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    OrderCart selectByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int updateByPrimaryKeySelective(OrderCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(OrderCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_cart
     *
     * @mbg.generated Thu Apr 25 20:36:37 CST 2019
     */
    int updateByPrimaryKey(OrderCart record);

    @Select("select * from order_cart where customer_id = #{uid}")
    List<OrderCart> selectByUserID(@Param("uid") Integer uid);

    List<OrderCart> getAllOrderCartByBatch(@Param("list") List<Integer> list);

    void deleteRoleBatchByBatch(@Param("list") List<Integer> list);
}