package it.qsbl.com.dao;

import it.qsbl.com.domain.ProductRicInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ProductRicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int deleteByPrimaryKey(String productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int insert(ProductRicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int insertSelective(ProductRicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    ProductRicInfo selectByPrimaryKey(String productPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int updateByPrimaryKeySelective(ProductRicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pic_info
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int updateByPrimaryKey(ProductRicInfo record);
}