package it.qsbl.com.dao;

import it.qsbl.com.domain.ProductComment;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ProductCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int insert(ProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int insertSelective(ProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    ProductComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int updateByPrimaryKeySelective(ProductComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comment
     *
     * @mbg.generated Fri Apr 19 15:03:30 CST 2019
     */
    int updateByPrimaryKey(ProductComment record);
}