package it.qsbl.com.dao;


import it.qsbl.com.domain.SubwayStation;

public interface SubwayStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int insert(SubwayStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int insertSelective(SubwayStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    SubwayStation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int updateByPrimaryKeySelective(SubwayStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subway_station
     *
     * @mbg.generated Wed Apr 17 16:14:53 CST 2019
     */
    int updateByPrimaryKey(SubwayStation record);
}